title:            Blog
description:      "Jay Varner"
logo:             logo.png
disqus_shortname: jayvarner
share:            true
dropcap:			true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:        	  ""

# Owner/author information
owner:
  name:           Jay Varner
  description:    Full Stack Sofware Engineer, master's student in user experience design
  # Social networking links used in footer. Update and remove as you like.
  twitter:        jayvarner
  github:         jayvarner

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-78194842-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
# highlighter: rouge
# markdown:    redcarpet
paginate:    5
paginate_path: "page:num"

# kramdown:
#     input: GFM



# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   :year/:month/:day/:slug

# syntax_highlighter_opts:
#     # Rouge Options › https://github.com/jneen/rouge#full-options
#     css_class: 'highlight'
#     #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
#     span:
#       line_numbers: false
#     block:
#       line_numbers: true
#       start_line: 1

# kramdown:
#     input: GFM
#     auto_ids: true
#     footnote_nr: 1
#     entity_output: as_char
#     toc_levels: 1..6

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

syntax_highlighter_opts:
    disable: true
    css_class: 'codehilite'

prose:
  rooturl: '_posts'
  siteurl: 'http://jayvarner.io'
  relativeLinks: 'http://jayvarner.io/links.jsonp'
  media: 'images'

gems:
    - jekyll-paginate
    - zurb-foundation
include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
